# Hostname of the server, used to generate bounced email return addresses
hostname: phillydragonboat.info
# on - enable automatically switching to secure server
# off - disable automatically switching to secure server
SSL: on


admin_per_page: 50
news_per_page: 5


#TODO: change to no-reply@philadragonboatfestival.com
noreply_email: noreply@phillydragonboat.info 
admin_email: admin@phillydragonboat.info
order_email: orders@phillydragonboat.info

